### PR TITLE
added eval

### PR DESCRIPTION
**Pull request by UnityLxthel**

### CODE REVIEW

**Comment by UnityLxthel** [comment]
:> im a chad

**Comment by superdan272727** [comment]
no bye

**Comment by somerandomcloud** [comment]
What a nerd

**Comment by WilsontheWolf** [comment]
Claims they are a chad
also adds a .replit file.

**Comment by UnityLxthel** [comment]
📦

**Comment by alhassanv** [comment]
Has this been tested? Could you show images of it working?

**Comment by UnityLxthel** [comment]
yes

**Review by alhassanv — APPROVED** [review]

**Review by alhassanv — APPROVED** [review]

**Pull request merged**
